name: Portfolio_action

on:
  push:
    branches: 
      - deploy
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: node 버전 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # - name: 캐싱 작업
      #   uses: actions/cache@v2
      #   with:
      #     path: cache
      #     key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn-lock') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-yarn-

      - name: yarn 설치
        run: npm install -g yarn
  
      - name: 리액트 패키지 설치
        run: yarn install
    
      - name: 리액트 빌드
        run: yarn build
        env:
          CI: false
      
      - name: S3 업로드
        run: aws s3 sync build/ s3://ansooportfoliobucket --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
      - name: CloudFront 캐시 무력화 설정
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}